# Generated by Django 5.1.7 on 2025-04-11 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artikel',
            old_name='tanggal',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='artikel',
            old_name='penulis',
            new_name='created_by',
        ),
        migrations.AddField(
            model_name='artikel',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
