# Generated by Django 5.1.7 on 2025-04-19 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0002_rename_tanggal_artikel_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to='gambar_artikel/'),
        ),
    ]
