# Generated by Django 5.1.7 on 2025-04-19 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0003_artikel_gambar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Komentar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('isi', models.TextField()),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('artikel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komentar', to='artikel.artikel')),
            ],
        ),
    ]
