# Generated by Django 5.1.7 on 2025-04-19 01:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0004_komentar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artikel',
            new_name='Post',
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Post'},
        ),
        migrations.RenameField(
            model_name='komentar',
            old_name='artikel',
            new_name='post',
        ),
    ]
