# Generated by Django 5.1.7 on 2025-04-19 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0005_rename_artikel_post_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
