# Generated by Django 5.1.7 on 2025-05-30 02:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0007_kategori_created_at_kategori_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='ArtikelBlog',
        ),
        migrations.RenameField(
            model_name='komentar',
            old_name='post',
            new_name='ArtikelBlog',
        ),
    ]
