# Generated by Django 5.0.1 on 2025-05-31 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0008_rename_post_artikelblog_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artikelblog',
            old_name='isi',
            new_name='konten',
        ),
    ]
