# Generated by Django 5.0.1 on 2025-05-31 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0009_rename_isi_artikelblog_konten'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artikelblog',
            old_name='konten',
            new_name='isi',
        ),
    ]
