# Generated by Django 5.0.1 on 2025-06-26 08:56

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0010_rename_konten_artikelblog_isi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='komentar',
            old_name='ArtikelBlog',
            new_name='artikel',
        ),
        migrations.AlterField(
            model_name='artikelblog',
            name='isi',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Isi Artikel'),
        ),
    ]
