# Generated by Django 5.0.1 on 2025-06-26 09:00

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0011_rename_artikelblog_komentar_artikel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikelblog',
            name='isi',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Konten'),
        ),
    ]
